import { useContext } from "react";
import { TailwindConfigContext } from "contexts";
import "tailwindcss/dist/tailwind.min.css";


export default function Home() {
  const [tailwindConfig, ] = useContext(TailwindConfigContext);
  return (
    <div className="">
        <main className="my-8 mx-4">
          <h2 className="text-4xl ">Custom tailwindcss config Documentation</h2>
          <p className="mt-4 ">
            The problem i am trying to solve is to have an exhaustive list of all the CSS classes being 
            generated by tailwind when we use a custom tailwind config. For eg. based on the Design tokens 
            we adopt, the http://tailwindcss.com/ documentation becomes no longer fully valid.
          </p>
        </main>
    </div>
  );
}
